services:
  postgres:
    image: postgres:16-alpine
    container_name: remtx-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: remtx
      POSTGRES_PASSWORD: remtx
      POSTGRES_DB: remtx
    ports:
      - "5432:5432"
    volumes:
      - remtx_pgdata:/var/lib/postgresql/data

volumes:
  remtx_pgdata:
