export type {
  UserRole,
  StatusVeiculo,
  PorteVeiculo,
  StatusLocacao,
  TipoEventoAgenda,
  TipoTransacao,
  FormaPagamento,
  AlertaManutencao,
  GravidadeProblema,
  TipoModeloContrato,
  StatusContratoDocumento,
  StatusPlanoConquista,
  PeriodicidadePagamento,
} from "@/generated/prisma/enums";
